version: '3.7'
services:

  millennial_investor:
    stdin_open: true
    container_name: millennial_investor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true